services:
  - type: web
    name: denoise-app
    env: node
    branch: deploy-fix
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: JWT_SECRET
        generateValue: true
