services:
  - type: web
    name: denoise-app
    runtime: node
    plan: free
    branch: deploy-fix
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
    numInstances: 1
